In [1]:
import pandas as pd
import numpy as np

In [14]:
dataset=pd.read_csv('MOVIE.csv')

In [15]:
dataset.shape

(15, 2)

In [16]:
dataset

Review  Class
0   This is such a good movie. I'm huge fan of the...      1
1                       Amazing movie. Worth watching      1
2                 what a movie!!!! Absulately love it      1
3          Very good movie.I would love to rewatch it      1
4        what a amazing acting. Loved the whole story      1
5                                  Worst movie so far      2
6                      Vey bad movie. I don't like it      2
7     I like the movie.I will definately recommend it      1
8                 So boring movie. Not worth watching      2
9   bad acting , worst director. Everything is so ...      2
10          Literally waste my time. Not a good movie      2
11               amazing, amazing. I will rewatch it.      1
12  disguisting acting by the hero. Won't reccomen...      2
13  Disappointed by the actor. Wasted 2 hours of m...      2
14                  love the movie. Will Recommend it      1

# Data cleaning

In [18]:
pip install nltk



     ---------------------------------------- 1.5/1.5 MB 55.9 kB/s eta 0:00:00
     ------------------------------------- 267.7/267.7 kB 74.2 kB/s eta 0:00:00
     --------------------------------------- 78.5/78.5 kB 58.3 kB/s eta 0:00:00


In [19]:
import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


ps=PorterStemmer()
all_stopwords=stopwords.words('english')
all_stopwords.remove('not')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [20]:
all_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [21]:
corpus=[]

for i in range(0,15):
    review= re.sub('[^a-zA-z]',' ', dataset['Review'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(all_stopwords)]
    review= ' '.join(review)
    corpus.append(review)

In [22]:
corpus

['good movi huge fan hero',
 'amaz movi worth watch',
 'movi absul love',
 'good movi would love rewatch',
 'amaz act love whole stori',
 'worst movi far',
 'vey bad movi like',
 'like movi defin recommend',
 'bore movi not worth watch',
 'bad act worst director everyth bore movi disppoint',
 'liter wast time not good movi',
 'amaz amaz rewatch',
 'disguist act hero reccomend',
 'disappoint actor wast hour life',
 'love movi recommend']

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [24]:
x= vectorizer.fit_transform(corpus).toarray()
y=dataset.iloc[:,1].values

In [25]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],


In [26]:
y

array([1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1], dtype=int64)

In [43]:
import pickle
path="\IMAGE CLASSIFICATION USING CNN KERAS\bow.pkl"
pickle.dump(vectorizer,open(path,"wb"))

OSError: [Errno 22] Invalid argument: '\\IMAGE CLASSIFICATION USING CNN KERAS\x08ow.pkl'

# training

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_text,y_train,y_text=train_test_split(x , y, test_size=0.3, random_state=0)

In [32]:
x.shape

(15, 36)

In [33]:
y.shape

(15,)

In [34]:
x_train.shape

(10, 36)

In [35]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)


GaussianNB()

In [36]:
prediction=classifier.predict(x_text)

In [37]:
prediction

array([1, 1, 2, 2, 1], dtype=int64)

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_text,prediction)

In [39]:
print(cm)
accuracy_score(y_text,prediction)

[[2 0]
 [1 2]]


0.8

In [41]:
path="C:\Users\ADMIN\Desktop\IMAGE CLASSIFICATION USING CNN KERAS\L\Movie-review-analysis-main\model.pkl"
pickle.dump(classifier,open(path,"wb"))

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3079697221.py, line 1)